### PR TITLE
Local .gitignore rules files

### PR DESCRIPTION
**Pull request by DavidS-ovm**
### Changes

Add the possibility to extend the .gitignore file with local rules.

### Type of change

* New feature (non-breaking change which adds functionality)

## Why

`habits/install` unconditionally overwrites `.gitignore` with templated content. This happens as `postStartCommand`, and therefore rather too often.

### CODE REVIEW

**Comment by valter-silva-au** [comment]
Hi @DavidS-om , thank you for opening the PR!
I would like to understand a bit more the use case. Could you please explain it a bit more?

From my view, the `.gitginore` is already being tracked by `git`, so any modification to it would be detected by the user. So, I would like to avoid appending any additional, and potentially duplicated rules to `.gitignore`.
I could remove the target `gitignore/init` from the `habits/init` target, I think that would make more sense.

Also, `habits/init` should be executed only once, in order to initialize all the files required by the organization (e.g.: default `.pre-commit-config.yml`, `.gitignore` and son). Thus allowing modifications later done by the users.

What are you thoughts?

**Comment by DavidS-ovm** [comment]
Oh, I might have been confused between repos here. I've used awslabs/aws-terraform-dev-container to setup the devcontainer and it runs `habits/install` everytime the container starts: 

https://github.com/awslabs/aws-terraform-dev-container/blob/ab16ec3d017e3bd209cf4e1ddb3b3f01b5817c2e/.devcontainer/devcontainer.json#L14

This causes any changes in gitignore to be overwritten.

Yes, I can see it happening through git, but having to manually revert it every time is tedious and error-prone.

**Comment by valter-silva-au** [comment]
Hi @DavidS-om , thank you for letting me know! I've fixed [both issues now](https://github.com/awslabs/aws-terraform-dev-container/commits/main). I'm closing this PR, let me know if the issue persists by re-opening it. Thank you!

**Comment by DavidS-ovm** [comment]
Yeah that has worked and fixed the issue. Thanks a lot for the quick response!

**Pull request closed without merging**
